<?php

namespace Database\Seeders;

use App\Models\Catalogos\DepartamentoGeografico;
use App\Models\Catalogos\Municipio;
use Illuminate\Database\Seeder;

class MunicipioSeeder extends Seeder
{
    public function run(): void
    {
        $municipios = $this->getMunicipios();

        foreach ($municipios as $data) {
            $departamento = DepartamentoGeografico::where('codigo', $data['departamento_geo_id'])->first();
            if ($departamento) {
                Municipio::firstOrCreate(
                    ['codigo' => $data['codigo']],
                    [
                        'departamento_geo_id' => $departamento->id,
                        'nombre' => $data['nombre'],
                    ]
                );
            }
        }
    }

    private function getMunicipios(): array
    {
        return [
            // Guatemala (01)
            ['departamento_geo_id' => '01', 'codigo' => '0101', 'nombre' => 'Guatemala'],
            ['departamento_geo_id' => '01', 'codigo' => '0102', 'nombre' => 'Santa Catarina Pinula'],
            ['departamento_geo_id' => '01', 'codigo' => '0103', 'nombre' => 'San José Pinula'],
            ['departamento_geo_id' => '01', 'codigo' => '0104', 'nombre' => 'San José del Golfo'],
            ['departamento_geo_id' => '01', 'codigo' => '0105', 'nombre' => 'Palencia'],
            ['departamento_geo_id' => '01', 'codigo' => '0106', 'nombre' => 'Chinautla'],
            ['departamento_geo_id' => '01', 'codigo' => '0107', 'nombre' => 'San Pedro Ayampuc'],
            ['departamento_geo_id' => '01', 'codigo' => '0108', 'nombre' => 'Mixco'],
            ['departamento_geo_id' => '01', 'codigo' => '0109', 'nombre' => 'San Pedro Sacatepéquez'],
            ['departamento_geo_id' => '01', 'codigo' => '0110', 'nombre' => 'San Juan Sacatepéquez'],
            ['departamento_geo_id' => '01', 'codigo' => '0111', 'nombre' => 'San Raymundo'],
            ['departamento_geo_id' => '01', 'codigo' => '0112', 'nombre' => 'Chuarrancho'],
            ['departamento_geo_id' => '01', 'codigo' => '0113', 'nombre' => 'Fraijanes'],
            ['departamento_geo_id' => '01', 'codigo' => '0114', 'nombre' => 'Amatitlán'],
            ['departamento_geo_id' => '01', 'codigo' => '0115', 'nombre' => 'Villa Nueva'],
            ['departamento_geo_id' => '01', 'codigo' => '0116', 'nombre' => 'Villa Canales'],
            ['departamento_geo_id' => '01', 'codigo' => '0117', 'nombre' => 'San Miguel Petapa'],

            // El Progreso (02)
            ['departamento_geo_id' => '02', 'codigo' => '0201', 'nombre' => 'Guastatoya'],
            ['departamento_geo_id' => '02', 'codigo' => '0202', 'nombre' => 'Morazán'],
            ['departamento_geo_id' => '02', 'codigo' => '0203', 'nombre' => 'San Agustín Acasaguastlán'],
            ['departamento_geo_id' => '02', 'codigo' => '0204', 'nombre' => 'San Cristóbal Acasaguastlán'],
            ['departamento_geo_id' => '02', 'codigo' => '0205', 'nombre' => 'El Jícaro'],
            ['departamento_geo_id' => '02', 'codigo' => '0206', 'nombre' => 'Sansare'],
            ['departamento_geo_id' => '02', 'codigo' => '0207', 'nombre' => 'Sanarate'],
            ['departamento_geo_id' => '02', 'codigo' => '0208', 'nombre' => 'San Antonio La Paz'],

            // Sacatepéquez (03)
            ['departamento_geo_id' => '03', 'codigo' => '0301', 'nombre' => 'Antigua Guatemala'],
            ['departamento_geo_id' => '03', 'codigo' => '0302', 'nombre' => 'Jocotenango'],
            ['departamento_geo_id' => '03', 'codigo' => '0303', 'nombre' => 'Pastores'],
            ['departamento_geo_id' => '03', 'codigo' => '0304', 'nombre' => 'Sumpango'],
            ['departamento_geo_id' => '03', 'codigo' => '0305', 'nombre' => 'Santo Domingo Xenacoj'],
            ['departamento_geo_id' => '03', 'codigo' => '0306', 'nombre' => 'Santiago Sacatepéquez'],
            ['departamento_geo_id' => '03', 'codigo' => '0307', 'nombre' => 'San Bartolomé Milpas Altas'],
            ['departamento_geo_id' => '03', 'codigo' => '0308', 'nombre' => 'San Lucas Sacatepéquez'],
            ['departamento_geo_id' => '03', 'codigo' => '0309', 'nombre' => 'Santa Lucía Milpas Altas'],
            ['departamento_geo_id' => '03', 'codigo' => '0310', 'nombre' => 'Magdalena Milpas Altas'],
            ['departamento_geo_id' => '03', 'codigo' => '0311', 'nombre' => 'Santa María de Jesús'],
            ['departamento_geo_id' => '03', 'codigo' => '0312', 'nombre' => 'Ciudad Vieja'],
            ['departamento_geo_id' => '03', 'codigo' => '0313', 'nombre' => 'San Miguel Dueñas'],
            ['departamento_geo_id' => '03', 'codigo' => '0314', 'nombre' => 'Alotenango'],
            ['departamento_geo_id' => '03', 'codigo' => '0315', 'nombre' => 'San Antonio Aguas Calientes'],
            ['departamento_geo_id' => '03', 'codigo' => '0316', 'nombre' => 'Santa Catarina Barahona'],

            // Chimaltenango (04)
            ['departamento_geo_id' => '04', 'codigo' => '0401', 'nombre' => 'Chimaltenango'],
            ['departamento_geo_id' => '04', 'codigo' => '0402', 'nombre' => 'San José Poaquil'],
            ['departamento_geo_id' => '04', 'codigo' => '0403', 'nombre' => 'San Martín Jilotepeque'],
            ['departamento_geo_id' => '04', 'codigo' => '0404', 'nombre' => 'San Juan Comalapa'],
            ['departamento_geo_id' => '04', 'codigo' => '0405', 'nombre' => 'Santa Apolonia'],
            ['departamento_geo_id' => '04', 'codigo' => '0406', 'nombre' => 'Tecpán'],
            ['departamento_geo_id' => '04', 'codigo' => '0407', 'nombre' => 'Patzún'],
            ['departamento_geo_id' => '04', 'codigo' => '0408', 'nombre' => 'San Miguel Pochuta'],
            ['departamento_geo_id' => '04', 'codigo' => '0409', 'nombre' => 'Patzicía'],
            ['departamento_geo_id' => '04', 'codigo' => '0410', 'nombre' => 'Santa Cruz Balanyá'],
            ['departamento_geo_id' => '04', 'codigo' => '0411', 'nombre' => 'Acatenango'],
            ['departamento_geo_id' => '04', 'codigo' => '0412', 'nombre' => 'San Pedro Yepocapa'],
            ['departamento_geo_id' => '04', 'codigo' => '0413', 'nombre' => 'San Andrés Itzapa'],
            ['departamento_geo_id' => '04', 'codigo' => '0414', 'nombre' => 'Parramos'],
            ['departamento_geo_id' => '04', 'codigo' => '0415', 'nombre' => 'Zaragoza'],
            ['departamento_geo_id' => '04', 'codigo' => '0416', 'nombre' => 'El Tejar'],

            // Escuintla (05)
            ['departamento_geo_id' => '05', 'codigo' => '0501', 'nombre' => 'Escuintla'],
            ['departamento_geo_id' => '05', 'codigo' => '0502', 'nombre' => 'Santa Lucía Cotzumalguapa'],
            ['departamento_geo_id' => '05', 'codigo' => '0503', 'nombre' => 'La Democracia'],
            ['departamento_geo_id' => '05', 'codigo' => '0504', 'nombre' => 'Siquinalá'],
            ['departamento_geo_id' => '05', 'codigo' => '0505', 'nombre' => 'Masagua'],
            ['departamento_geo_id' => '05', 'codigo' => '0506', 'nombre' => 'Tiquisate'],
            ['departamento_geo_id' => '05', 'codigo' => '0507', 'nombre' => 'La Gomera'],
            ['departamento_geo_id' => '05', 'codigo' => '0508', 'nombre' => 'Guanagazapa'],
            ['departamento_geo_id' => '05', 'codigo' => '0509', 'nombre' => 'San José'],
            ['departamento_geo_id' => '05', 'codigo' => '0510', 'nombre' => 'Iztapa'],
            ['departamento_geo_id' => '05', 'codigo' => '0511', 'nombre' => 'Palín'],
            ['departamento_geo_id' => '05', 'codigo' => '0512', 'nombre' => 'San Vicente Pacaya'],
            ['departamento_geo_id' => '05', 'codigo' => '0513', 'nombre' => 'Nueva Concepción'],

            // Santa Rosa (06)
            ['departamento_geo_id' => '06', 'codigo' => '0601', 'nombre' => 'Cuilapa'],
            ['departamento_geo_id' => '06', 'codigo' => '0602', 'nombre' => 'Barberena'],
            ['departamento_geo_id' => '06', 'codigo' => '0603', 'nombre' => 'Santa Rosa de Lima'],
            ['departamento_geo_id' => '06', 'codigo' => '0604', 'nombre' => 'Casillas'],
            ['departamento_geo_id' => '06', 'codigo' => '0605', 'nombre' => 'San Rafael Las Flores'],
            ['departamento_geo_id' => '06', 'codigo' => '0606', 'nombre' => 'Oratorio'],
            ['departamento_geo_id' => '06', 'codigo' => '0607', 'nombre' => 'San Juan Tecuaco'],
            ['departamento_geo_id' => '06', 'codigo' => '0608', 'nombre' => 'Chiquimulilla'],
            ['departamento_geo_id' => '06', 'codigo' => '0609', 'nombre' => 'Taxisco'],
            ['departamento_geo_id' => '06', 'codigo' => '0610', 'nombre' => 'Santa María Ixhuatán'],
            ['departamento_geo_id' => '06', 'codigo' => '0611', 'nombre' => 'Guazacapán'],
            ['departamento_geo_id' => '06', 'codigo' => '0612', 'nombre' => 'Santa Cruz Naranjo'],
            ['departamento_geo_id' => '06', 'codigo' => '0613', 'nombre' => 'Pueblo Nuevo Viñas'],
            ['departamento_geo_id' => '06', 'codigo' => '0614', 'nombre' => 'Nueva Santa Rosa'],

            // Sololá (07)
            ['departamento_geo_id' => '07', 'codigo' => '0701', 'nombre' => 'Sololá'],
            ['departamento_geo_id' => '07', 'codigo' => '0702', 'nombre' => 'San José Chacayá'],
            ['departamento_geo_id' => '07', 'codigo' => '0703', 'nombre' => 'Santa María Visitación'],
            ['departamento_geo_id' => '07', 'codigo' => '0704', 'nombre' => 'Santa Lucía Utatlán'],
            ['departamento_geo_id' => '07', 'codigo' => '0705', 'nombre' => 'Nahualá'],
            ['departamento_geo_id' => '07', 'codigo' => '0706', 'nombre' => 'Santa Catarina Ixtahuacán'],
            ['departamento_geo_id' => '07', 'codigo' => '0707', 'nombre' => 'Santa Clara La Laguna'],
            ['departamento_geo_id' => '07', 'codigo' => '0708', 'nombre' => 'Concepción'],
            ['departamento_geo_id' => '07', 'codigo' => '0709', 'nombre' => 'San Andrés Semetabaj'],
            ['departamento_geo_id' => '07', 'codigo' => '0710', 'nombre' => 'Panajachel'],
            ['departamento_geo_id' => '07', 'codigo' => '0711', 'nombre' => 'Santa Catarina Palopó'],
            ['departamento_geo_id' => '07', 'codigo' => '0712', 'nombre' => 'San Antonio Palopó'],
            ['departamento_geo_id' => '07', 'codigo' => '0713', 'nombre' => 'San Lucas Tolimán'],
            ['departamento_geo_id' => '07', 'codigo' => '0714', 'nombre' => 'Santa Cruz La Laguna'],
            ['departamento_geo_id' => '07', 'codigo' => '0715', 'nombre' => 'San Pablo La Laguna'],
            ['departamento_geo_id' => '07', 'codigo' => '0716', 'nombre' => 'San Marcos La Laguna'],
            ['departamento_geo_id' => '07', 'codigo' => '0717', 'nombre' => 'San Juan La Laguna'],
            ['departamento_geo_id' => '07', 'codigo' => '0718', 'nombre' => 'San Pedro La Laguna'],
            ['departamento_geo_id' => '07', 'codigo' => '0719', 'nombre' => 'Santiago Atitlán'],

            // Totonicapán (08)
            ['departamento_geo_id' => '08', 'codigo' => '0801', 'nombre' => 'Totonicapán'],
            ['departamento_geo_id' => '08', 'codigo' => '0802', 'nombre' => 'San Cristóbal Totonicapán'],
            ['departamento_geo_id' => '08', 'codigo' => '0803', 'nombre' => 'San Francisco El Alto'],
            ['departamento_geo_id' => '08', 'codigo' => '0804', 'nombre' => 'San Andrés Xecul'],
            ['departamento_geo_id' => '08', 'codigo' => '0805', 'nombre' => 'Momostenango'],
            ['departamento_geo_id' => '08', 'codigo' => '0806', 'nombre' => 'Santa María Chiquimula'],
            ['departamento_geo_id' => '08', 'codigo' => '0807', 'nombre' => 'Santa Lucía La Reforma'],
            ['departamento_geo_id' => '08', 'codigo' => '0808', 'nombre' => 'San Bartolo'],

            // Quetzaltenango (09)
            ['departamento_geo_id' => '09', 'codigo' => '0901', 'nombre' => 'Quetzaltenango'],
            ['departamento_geo_id' => '09', 'codigo' => '0902', 'nombre' => 'Salcajá'],
            ['departamento_geo_id' => '09', 'codigo' => '0903', 'nombre' => 'Olintepeque'],
            ['departamento_geo_id' => '09', 'codigo' => '0904', 'nombre' => 'San Carlos Sija'],
            ['departamento_geo_id' => '09', 'codigo' => '0905', 'nombre' => 'Sibilia'],
            ['departamento_geo_id' => '09', 'codigo' => '0906', 'nombre' => 'Cabricán'],
            ['departamento_geo_id' => '09', 'codigo' => '0907', 'nombre' => 'Cajolá'],
            ['departamento_geo_id' => '09', 'codigo' => '0908', 'nombre' => 'San Miguel Sigüilá'],
            ['departamento_geo_id' => '09', 'codigo' => '0909', 'nombre' => 'San Juan Ostuncalco'],
            ['departamento_geo_id' => '09', 'codigo' => '0910', 'nombre' => 'San Mateo'],
            ['departamento_geo_id' => '09', 'codigo' => '0911', 'nombre' => 'Concepción Chiquirichapa'],
            ['departamento_geo_id' => '09', 'codigo' => '0912', 'nombre' => 'San Martín Sacatepéquez'],
            ['departamento_geo_id' => '09', 'codigo' => '0913', 'nombre' => 'Almolonga'],
            ['departamento_geo_id' => '09', 'codigo' => '0914', 'nombre' => 'Cantel'],
            ['departamento_geo_id' => '09', 'codigo' => '0915', 'nombre' => 'Huitán'],
            ['departamento_geo_id' => '09', 'codigo' => '0916', 'nombre' => 'Zunil'],
            ['departamento_geo_id' => '09', 'codigo' => '0917', 'nombre' => 'Colomba Costa Cuca'],
            ['departamento_geo_id' => '09', 'codigo' => '0918', 'nombre' => 'San Francisco La Unión'],
            ['departamento_geo_id' => '09', 'codigo' => '0919', 'nombre' => 'El Palmar'],
            ['departamento_geo_id' => '09', 'codigo' => '0920', 'nombre' => 'Coatepeque'],
            ['departamento_geo_id' => '09', 'codigo' => '0921', 'nombre' => 'Génova'],
            ['departamento_geo_id' => '09', 'codigo' => '0922', 'nombre' => 'Flores Costa Cuca'],
            ['departamento_geo_id' => '09', 'codigo' => '0923', 'nombre' => 'La Esperanza'],
            ['departamento_geo_id' => '09', 'codigo' => '0924', 'nombre' => 'Palestina de Los Altos'],

            // Suchitepéquez (10)
            ['departamento_geo_id' => '10', 'codigo' => '1001', 'nombre' => 'Mazatenango'],
            ['departamento_geo_id' => '10', 'codigo' => '1002', 'nombre' => 'Cuyotenango'],
            ['departamento_geo_id' => '10', 'codigo' => '1003', 'nombre' => 'San Francisco Zapotitlán'],
            ['departamento_geo_id' => '10', 'codigo' => '1004', 'nombre' => 'San Bernardino'],
            ['departamento_geo_id' => '10', 'codigo' => '1005', 'nombre' => 'San José El Ídolo'],
            ['departamento_geo_id' => '10', 'codigo' => '1006', 'nombre' => 'Santo Domingo Suchitepéquez'],
            ['departamento_geo_id' => '10', 'codigo' => '1007', 'nombre' => 'San Lorenzo'],
            ['departamento_geo_id' => '10', 'codigo' => '1008', 'nombre' => 'Samayac'],
            ['departamento_geo_id' => '10', 'codigo' => '1009', 'nombre' => 'San Pablo Jocopilas'],
            ['departamento_geo_id' => '10', 'codigo' => '1010', 'nombre' => 'San Antonio Suchitepéquez'],
            ['departamento_geo_id' => '10', 'codigo' => '1011', 'nombre' => 'San Miguel Panán'],
            ['departamento_geo_id' => '10', 'codigo' => '1012', 'nombre' => 'San Gabriel'],
            ['departamento_geo_id' => '10', 'codigo' => '1013', 'nombre' => 'Chicacao'],
            ['departamento_geo_id' => '10', 'codigo' => '1014', 'nombre' => 'Patulul'],
            ['departamento_geo_id' => '10', 'codigo' => '1015', 'nombre' => 'Santa Bárbara'],
            ['departamento_geo_id' => '10', 'codigo' => '1016', 'nombre' => 'San Juan Bautista'],
            ['departamento_geo_id' => '10', 'codigo' => '1017', 'nombre' => 'Santo Tomás La Unión'],
            ['departamento_geo_id' => '10', 'codigo' => '1018', 'nombre' => 'Zunilito'],
            ['departamento_geo_id' => '10', 'codigo' => '1019', 'nombre' => 'Pueblo Nuevo'],
            ['departamento_geo_id' => '10', 'codigo' => '1020', 'nombre' => 'Río Bravo'],

            // Retalhuleu (11)
            ['departamento_geo_id' => '11', 'codigo' => '1101', 'nombre' => 'Retalhuleu'],
            ['departamento_geo_id' => '11', 'codigo' => '1102', 'nombre' => 'San Sebastián'],
            ['departamento_geo_id' => '11', 'codigo' => '1103', 'nombre' => 'Santa Cruz Muluá'],
            ['departamento_geo_id' => '11', 'codigo' => '1104', 'nombre' => 'San Martín Zapotitlán'],
            ['departamento_geo_id' => '11', 'codigo' => '1105', 'nombre' => 'San Felipe'],
            ['departamento_geo_id' => '11', 'codigo' => '1106', 'nombre' => 'San Andrés Villa Seca'],
            ['departamento_geo_id' => '11', 'codigo' => '1107', 'nombre' => 'Champerico'],
            ['departamento_geo_id' => '11', 'codigo' => '1108', 'nombre' => 'Nuevo San Carlos'],
            ['departamento_geo_id' => '11', 'codigo' => '1109', 'nombre' => 'El Asintal'],

            // San Marcos (12)
            ['departamento_geo_id' => '12', 'codigo' => '1201', 'nombre' => 'San Marcos'],
            ['departamento_geo_id' => '12', 'codigo' => '1202', 'nombre' => 'San Pedro Sacatepéquez'],
            ['departamento_geo_id' => '12', 'codigo' => '1203', 'nombre' => 'San Antonio Sacatepéquez'],
            ['departamento_geo_id' => '12', 'codigo' => '1204', 'nombre' => 'Comitancillo'],
            ['departamento_geo_id' => '12', 'codigo' => '1205', 'nombre' => 'San Miguel Ixtahuacán'],
            ['departamento_geo_id' => '12', 'codigo' => '1206', 'nombre' => 'Concepción Tutuapa'],
            ['departamento_geo_id' => '12', 'codigo' => '1207', 'nombre' => 'Tacaná'],
            ['departamento_geo_id' => '12', 'codigo' => '1208', 'nombre' => 'Sibinal'],
            ['departamento_geo_id' => '12', 'codigo' => '1209', 'nombre' => 'Tajumulco'],
            ['departamento_geo_id' => '12', 'codigo' => '1210', 'nombre' => 'Tejutla'],
            ['departamento_geo_id' => '12', 'codigo' => '1211', 'nombre' => 'San Rafael Pie de La Cuesta'],
            ['departamento_geo_id' => '12', 'codigo' => '1212', 'nombre' => 'Nuevo Progreso'],
            ['departamento_geo_id' => '12', 'codigo' => '1213', 'nombre' => 'El Tumbador'],
            ['departamento_geo_id' => '12', 'codigo' => '1214', 'nombre' => 'San José El Rodeo'],
            ['departamento_geo_id' => '12', 'codigo' => '1215', 'nombre' => 'Malacatán'],
            ['departamento_geo_id' => '12', 'codigo' => '1216', 'nombre' => 'Catarina'],
            ['departamento_geo_id' => '12', 'codigo' => '1217', 'nombre' => 'Ayutla'],
            ['departamento_geo_id' => '12', 'codigo' => '1218', 'nombre' => 'Ocós'],
            ['departamento_geo_id' => '12', 'codigo' => '1219', 'nombre' => 'San Pablo'],
            ['departamento_geo_id' => '12', 'codigo' => '1220', 'nombre' => 'El Quetzal'],
            ['departamento_geo_id' => '12', 'codigo' => '1221', 'nombre' => 'La Reforma'],
            ['departamento_geo_id' => '12', 'codigo' => '1222', 'nombre' => 'Pajapita'],
            ['departamento_geo_id' => '12', 'codigo' => '1223', 'nombre' => 'Ixchiguán'],
            ['departamento_geo_id' => '12', 'codigo' => '1224', 'nombre' => 'San José Ojetenam'],
            ['departamento_geo_id' => '12', 'codigo' => '1225', 'nombre' => 'San Cristóbal Cucho'],
            ['departamento_geo_id' => '12', 'codigo' => '1226', 'nombre' => 'Sipacapa'],
            ['departamento_geo_id' => '12', 'codigo' => '1227', 'nombre' => 'Esquipulas Palo Gordo'],
            ['departamento_geo_id' => '12', 'codigo' => '1228', 'nombre' => 'Río Blanco'],
            ['departamento_geo_id' => '12', 'codigo' => '1229', 'nombre' => 'San Lorenzo'],

            // Huehuetenango (13)
            ['departamento_geo_id' => '13', 'codigo' => '1301', 'nombre' => 'Huehuetenango'],
            ['departamento_geo_id' => '13', 'codigo' => '1302', 'nombre' => 'Chiantla'],
            ['departamento_geo_id' => '13', 'codigo' => '1303', 'nombre' => 'Malacatancito'],
            ['departamento_geo_id' => '13', 'codigo' => '1304', 'nombre' => 'Cuilco'],
            ['departamento_geo_id' => '13', 'codigo' => '1305', 'nombre' => 'Nentón'],
            ['departamento_geo_id' => '13', 'codigo' => '1306', 'nombre' => 'San Pedro Necta'],
            ['departamento_geo_id' => '13', 'codigo' => '1307', 'nombre' => 'Jacaltenango'],
            ['departamento_geo_id' => '13', 'codigo' => '1308', 'nombre' => 'Soloma'],
            ['departamento_geo_id' => '13', 'codigo' => '1309', 'nombre' => 'Ixtahuacán'],
            ['departamento_geo_id' => '13', 'codigo' => '1310', 'nombre' => 'Santa Bárbara'],
            ['departamento_geo_id' => '13', 'codigo' => '1311', 'nombre' => 'La Libertad'],
            ['departamento_geo_id' => '13', 'codigo' => '1312', 'nombre' => 'La Democracia'],
            ['departamento_geo_id' => '13', 'codigo' => '1313', 'nombre' => 'San Miguel Acatán'],
            ['departamento_geo_id' => '13', 'codigo' => '1314', 'nombre' => 'San Rafael La Independencia'],
            ['departamento_geo_id' => '13', 'codigo' => '1315', 'nombre' => 'Todos Santos Cuchumatán'],
            ['departamento_geo_id' => '13', 'codigo' => '1316', 'nombre' => 'San Juan Atitán'],
            ['departamento_geo_id' => '13', 'codigo' => '1317', 'nombre' => 'Santa Eulalia'],
            ['departamento_geo_id' => '13', 'codigo' => '1318', 'nombre' => 'San Mateo Ixtatán'],
            ['departamento_geo_id' => '13', 'codigo' => '1319', 'nombre' => 'Colotenango'],
            ['departamento_geo_id' => '13', 'codigo' => '1320', 'nombre' => 'San Sebastián Huehuetenango'],
            ['departamento_geo_id' => '13', 'codigo' => '1321', 'nombre' => 'Tectitán'],
            ['departamento_geo_id' => '13', 'codigo' => '1322', 'nombre' => 'Concepción Huista'],
            ['departamento_geo_id' => '13', 'codigo' => '1323', 'nombre' => 'San Juan Ixcoy'],
            ['departamento_geo_id' => '13', 'codigo' => '1324', 'nombre' => 'San Antonio Huista'],
            ['departamento_geo_id' => '13', 'codigo' => '1325', 'nombre' => 'San Sebastián Coatán'],
            ['departamento_geo_id' => '13', 'codigo' => '1326', 'nombre' => 'Santa Cruz Barillas'],
            ['departamento_geo_id' => '13', 'codigo' => '1327', 'nombre' => 'Aguacatán'],
            ['departamento_geo_id' => '13', 'codigo' => '1328', 'nombre' => 'San Rafael Petzal'],
            ['departamento_geo_id' => '13', 'codigo' => '1329', 'nombre' => 'San Gaspar Ixchil'],
            ['departamento_geo_id' => '13', 'codigo' => '1330', 'nombre' => 'Santiago Chimaltenango'],
            ['departamento_geo_id' => '13', 'codigo' => '1331', 'nombre' => 'Santa Ana Huista'],
            ['departamento_geo_id' => '13', 'codigo' => '1332', 'nombre' => 'Unión Cantinil'],
            ['departamento_geo_id' => '13', 'codigo' => '1333', 'nombre' => 'Petatán'],

            // Quiché (14)
            ['departamento_geo_id' => '14', 'codigo' => '1401', 'nombre' => 'Santa Cruz del Quiché'],
            ['departamento_geo_id' => '14', 'codigo' => '1402', 'nombre' => 'Chiché'],
            ['departamento_geo_id' => '14', 'codigo' => '1403', 'nombre' => 'Chinique'],
            ['departamento_geo_id' => '14', 'codigo' => '1404', 'nombre' => 'Zacualpa'],
            ['departamento_geo_id' => '14', 'codigo' => '1405', 'nombre' => 'Chajul'],
            ['departamento_geo_id' => '14', 'codigo' => '1406', 'nombre' => 'Chichicastenango'],
            ['departamento_geo_id' => '14', 'codigo' => '1407', 'nombre' => 'Patzité'],
            ['departamento_geo_id' => '14', 'codigo' => '1408', 'nombre' => 'San Antonio Ilotenango'],
            ['departamento_geo_id' => '14', 'codigo' => '1409', 'nombre' => 'San Pedro Jocopilas'],
            ['departamento_geo_id' => '14', 'codigo' => '1410', 'nombre' => 'Cunén'],
            ['departamento_geo_id' => '14', 'codigo' => '1411', 'nombre' => 'San Juan Cotzal'],
            ['departamento_geo_id' => '14', 'codigo' => '1412', 'nombre' => 'Joyabaj'],
            ['departamento_geo_id' => '14', 'codigo' => '1413', 'nombre' => 'Nebaj'],
            ['departamento_geo_id' => '14', 'codigo' => '1414', 'nombre' => 'San Andrés Sajcabajá'],
            ['departamento_geo_id' => '14', 'codigo' => '1415', 'nombre' => 'Uspantán'],
            ['departamento_geo_id' => '14', 'codigo' => '1416', 'nombre' => 'Sacapulas'],
            ['departamento_geo_id' => '14', 'codigo' => '1417', 'nombre' => 'San Bartolomé Jocotenango'],
            ['departamento_geo_id' => '14', 'codigo' => '1418', 'nombre' => 'Canillá'],
            ['departamento_geo_id' => '14', 'codigo' => '1419', 'nombre' => 'Chicamán'],
            ['departamento_geo_id' => '14', 'codigo' => '1420', 'nombre' => 'Ixcán'],
            ['departamento_geo_id' => '14', 'codigo' => '1421', 'nombre' => 'Pachalum'],

            // Baja Verapaz (15)
            ['departamento_geo_id' => '15', 'codigo' => '1501', 'nombre' => 'Salamá'],
            ['departamento_geo_id' => '15', 'codigo' => '1502', 'nombre' => 'San Miguel Chicaj'],
            ['departamento_geo_id' => '15', 'codigo' => '1503', 'nombre' => 'Rabinal'],
            ['departamento_geo_id' => '15', 'codigo' => '1504', 'nombre' => 'Cubulco'],
            ['departamento_geo_id' => '15', 'codigo' => '1505', 'nombre' => 'Granados'],
            ['departamento_geo_id' => '15', 'codigo' => '1506', 'nombre' => 'El Chol'],
            ['departamento_geo_id' => '15', 'codigo' => '1507', 'nombre' => 'San Jerónimo'],
            ['departamento_geo_id' => '15', 'codigo' => '1508', 'nombre' => 'Purulhá'],

            // Alta Verapaz (16)
            ['departamento_geo_id' => '16', 'codigo' => '1601', 'nombre' => 'Cobán'],
            ['departamento_geo_id' => '16', 'codigo' => '1602', 'nombre' => 'Santa Cruz Verapaz'],
            ['departamento_geo_id' => '16', 'codigo' => '1603', 'nombre' => 'San Cristóbal Verapaz'],
            ['departamento_geo_id' => '16', 'codigo' => '1604', 'nombre' => 'Tactic'],
            ['departamento_geo_id' => '16', 'codigo' => '1605', 'nombre' => 'Tamahú'],
            ['departamento_geo_id' => '16', 'codigo' => '1606', 'nombre' => 'San Miguel Tucurú'],
            ['departamento_geo_id' => '16', 'codigo' => '1607', 'nombre' => 'Panzós'],
            ['departamento_geo_id' => '16', 'codigo' => '1608', 'nombre' => 'Senahú'],
            ['departamento_geo_id' => '16', 'codigo' => '1609', 'nombre' => 'San Pedro Carchá'],
            ['departamento_geo_id' => '16', 'codigo' => '1610', 'nombre' => 'San Juan Chamelco'],
            ['departamento_geo_id' => '16', 'codigo' => '1611', 'nombre' => 'San Agustín Lanquín'],
            ['departamento_geo_id' => '16', 'codigo' => '1612', 'nombre' => 'Santa María Cahabón'],
            ['departamento_geo_id' => '16', 'codigo' => '1613', 'nombre' => 'Chisec'],
            ['departamento_geo_id' => '16', 'codigo' => '1614', 'nombre' => 'Chahal'],
            ['departamento_geo_id' => '16', 'codigo' => '1615', 'nombre' => 'Fray Bartolomé de Las Casas'],
            ['departamento_geo_id' => '16', 'codigo' => '1616', 'nombre' => 'Santa Catalina La Tinta'],
            ['departamento_geo_id' => '16', 'codigo' => '1617', 'nombre' => 'Raxruhá'],

            // Petén (17)
            ['departamento_geo_id' => '17', 'codigo' => '1701', 'nombre' => 'Flores'],
            ['departamento_geo_id' => '17', 'codigo' => '1702', 'nombre' => 'San José'],
            ['departamento_geo_id' => '17', 'codigo' => '1703', 'nombre' => 'San Benito'],
            ['departamento_geo_id' => '17', 'codigo' => '1704', 'nombre' => 'San Andrés'],
            ['departamento_geo_id' => '17', 'codigo' => '1705', 'nombre' => 'La Libertad'],
            ['departamento_geo_id' => '17', 'codigo' => '1706', 'nombre' => 'San Francisco'],
            ['departamento_geo_id' => '17', 'codigo' => '1707', 'nombre' => 'Santa Ana'],
            ['departamento_geo_id' => '17', 'codigo' => '1708', 'nombre' => 'Dolores'],
            ['departamento_geo_id' => '17', 'codigo' => '1709', 'nombre' => 'San Luis'],
            ['departamento_geo_id' => '17', 'codigo' => '1710', 'nombre' => 'Sayaxché'],
            ['departamento_geo_id' => '17', 'codigo' => '1711', 'nombre' => 'Melchor de Mencos'],
            ['departamento_geo_id' => '17', 'codigo' => '1712', 'nombre' => 'Poptún'],
            ['departamento_geo_id' => '17', 'codigo' => '1713', 'nombre' => 'Las Cruces'],
            ['departamento_geo_id' => '17', 'codigo' => '1714', 'nombre' => 'El Chal'],

            // Izabal (18)
            ['departamento_geo_id' => '18', 'codigo' => '1801', 'nombre' => 'Puerto Barrios'],
            ['departamento_geo_id' => '18', 'codigo' => '1802', 'nombre' => 'Livingston'],
            ['departamento_geo_id' => '18', 'codigo' => '1803', 'nombre' => 'El Estor'],
            ['departamento_geo_id' => '18', 'codigo' => '1804', 'nombre' => 'Morales'],
            ['departamento_geo_id' => '18', 'codigo' => '1805', 'nombre' => 'Los Amates'],

            // Zacapa (19)
            ['departamento_geo_id' => '19', 'codigo' => '1901', 'nombre' => 'Zacapa'],
            ['departamento_geo_id' => '19', 'codigo' => '1902', 'nombre' => 'Estanzuela'],
            ['departamento_geo_id' => '19', 'codigo' => '1903', 'nombre' => 'Río Hondo'],
            ['departamento_geo_id' => '19', 'codigo' => '1904', 'nombre' => 'Gualán'],
            ['departamento_geo_id' => '19', 'codigo' => '1905', 'nombre' => 'Teculután'],
            ['departamento_geo_id' => '19', 'codigo' => '1906', 'nombre' => 'Usumatlán'],
            ['departamento_geo_id' => '19', 'codigo' => '1907', 'nombre' => 'Cabañas'],
            ['departamento_geo_id' => '19', 'codigo' => '1908', 'nombre' => 'San Diego'],
            ['departamento_geo_id' => '19', 'codigo' => '1909', 'nombre' => 'La Unión'],
            ['departamento_geo_id' => '19', 'codigo' => '1910', 'nombre' => 'Huité'],
            ['departamento_geo_id' => '19', 'codigo' => '1911', 'nombre' => 'San Jorge'],

            // Chiquimula (20)
            ['departamento_geo_id' => '20', 'codigo' => '2001', 'nombre' => 'Chiquimula'],
            ['departamento_geo_id' => '20', 'codigo' => '2002', 'nombre' => 'San José La Arada'],
            ['departamento_geo_id' => '20', 'codigo' => '2003', 'nombre' => 'San Juan Ermita'],
            ['departamento_geo_id' => '20', 'codigo' => '2004', 'nombre' => 'Jocotán'],
            ['departamento_geo_id' => '20', 'codigo' => '2005', 'nombre' => 'Camotán'],
            ['departamento_geo_id' => '20', 'codigo' => '2006', 'nombre' => 'Olopa'],
            ['departamento_geo_id' => '20', 'codigo' => '2007', 'nombre' => 'Esquipulas'],
            ['departamento_geo_id' => '20', 'codigo' => '2008', 'nombre' => 'Concepción Las Minas'],
            ['departamento_geo_id' => '20', 'codigo' => '2009', 'nombre' => 'Quezaltepeque'],
            ['departamento_geo_id' => '20', 'codigo' => '2010', 'nombre' => 'San Jacinto'],
            ['departamento_geo_id' => '20', 'codigo' => '2011', 'nombre' => 'Ipala'],

            // Jalapa (21)
            ['departamento_geo_id' => '21', 'codigo' => '2101', 'nombre' => 'Jalapa'],
            ['departamento_geo_id' => '21', 'codigo' => '2102', 'nombre' => 'San Pedro Pinula'],
            ['departamento_geo_id' => '21', 'codigo' => '2103', 'nombre' => 'San Luis Jilotepeque'],
            ['departamento_geo_id' => '21', 'codigo' => '2104', 'nombre' => 'San Manuel Chaparrón'],
            ['departamento_geo_id' => '21', 'codigo' => '2105', 'nombre' => 'San Carlos Alzatate'],
            ['departamento_geo_id' => '21', 'codigo' => '2106', 'nombre' => 'Monjas'],
            ['departamento_geo_id' => '21', 'codigo' => '2107', 'nombre' => 'Mataquescuintla'],

            // Jutiapa (22)
            ['departamento_geo_id' => '22', 'codigo' => '2201', 'nombre' => 'Jutiapa'],
            ['departamento_geo_id' => '22', 'codigo' => '2202', 'nombre' => 'El Progreso'],
            ['departamento_geo_id' => '22', 'codigo' => '2203', 'nombre' => 'Santa Catarina Mita'],
            ['departamento_geo_id' => '22', 'codigo' => '2204', 'nombre' => 'Agua Blanca'],
            ['departamento_geo_id' => '22', 'codigo' => '2205', 'nombre' => 'Asunción Mita'],
            ['departamento_geo_id' => '22', 'codigo' => '2206', 'nombre' => 'Yupiltepeque'],
            ['departamento_geo_id' => '22', 'codigo' => '2207', 'nombre' => 'Atescatempa'],
            ['departamento_geo_id' => '22', 'codigo' => '2208', 'nombre' => 'Jerez'],
            ['departamento_geo_id' => '22', 'codigo' => '2209', 'nombre' => 'El Adelanto'],
            ['departamento_geo_id' => '22', 'codigo' => '2210', 'nombre' => 'Zapotitlán'],
            ['departamento_geo_id' => '22', 'codigo' => '2211', 'nombre' => 'Comapa'],
            ['departamento_geo_id' => '22', 'codigo' => '2212', 'nombre' => 'Jalpatagua'],
            ['departamento_geo_id' => '22', 'codigo' => '2213', 'nombre' => 'Conguaco'],
            ['departamento_geo_id' => '22', 'codigo' => '2214', 'nombre' => 'Moyuta'],
            ['departamento_geo_id' => '22', 'codigo' => '2215', 'nombre' => 'Pasaco'],
            ['departamento_geo_id' => '22', 'codigo' => '2216', 'nombre' => 'San José Acatempa'],
            ['departamento_geo_id' => '22', 'codigo' => '2217', 'nombre' => 'Quesada'],
        ];
    }
}
